### PR TITLE
Update to user JupyterLab 3.0 and bundled javascript

### PR DESCRIPTION
**Pull request by matthewturk**
This starts the process of converting.

Some of these items will be reverted, but using the automatic conversion on the CLI confused me enough that I wanted the web UI to view the actual diffs.

### CODE REVIEW

**Comment by matthewturk** [comment]
So this builds, but I'm now not able to make it run on my machine.  I am actually not sure how this all works with the 4823942 versions of jupyter I have installed, etc, so I'm going to do some checking before I merge it.

**Comment by matthewturk** [comment]
I think that https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/83 is relevant, because I got very confused with why the plugin wasn't working, etc.  I'm pretty confident I've made a number of mistakes, but once that PR is finished I think I'll have a better basis for narrowing down the issues here.

**Comment by matthewturk** [comment]
Also I'm definitely going to squash these changes when they're ready.

**Comment by matthewturk** [comment]
Alright!  Now it works.  I also am able to build in place and get things to go!  I had to update to the most recent `ipycanvas` as well as fix some dependencies, but now it's going.  Yay!

**Comment by cphyc** [comment]
Just to comment that I tried this on my machine and it works if I do `pip install -e .` from the root folder! Hooray!

**Review by munkm — APPROVED** [review]

**Pull request merged**
